### See https://meerschaum.io/reference/compose/ for the compose schema.

project_name: bikewalkgreenville

root_dir: ./root

plugins_dir:
- ./.installed_plugins
- ./plugins

plugins: ['clone']

pipes:

  ### Parse the CSVs emailed by SCDPS
  - connector: "plugin:scdps"
    metric: "fatalities"
    location: "greenville"
    target: "scdps_fatalities_greenville"

  ### 
  - connector: "plugin:scdps"
    metric: "collisions"
    location: "sc"
    target: "scdps_collisions_sc"
    columns:
      datetime: "CrashDate"
      accident_number: "AccidentNumber"
      object_id: "OBJECTID"
    indices:
      county: "County"
    parameters:
      verify:
        chunk_days: 365

  - connector: "sql:bwg"
    metric:  "collisions"
    location: "greenville"
    target: "scdps_collisions_greenville"
    columns:
      datetime: "CrashDate"
      primary: "AccidentNumber"
      object_id: "OBJECTID"
    parameters:
      query: |-
        SELECT *
        FROM {{Pipe('plugin:scdps', 'collisions', 'sc')}}
        WHERE "County" = 'Greenville'

  - connector: "plugin:strava-metro"
    metric: "activities"
    location: "greenville"
    target: "strava_metro_activities"

  - connector: "plugin:strava-metro"
    metric: "osm_ids"
    location: "srt"
    target: "srt_osm_ids"
    columns:
      edge_uid: "edge_uid"
      osm_reference_id: "osm_reference_id"

  - connector: "plugin:brokenspoke-analyzer"
    metric: "neighborhood_overall_scores"
    location: "brokenspoke"
    target: "neighborhood_overall_scores"
    parameters:
      schema: "brokenspoke"

  - connector: "plugin:brokenspoke-analyzer"
    metric: "neighborhood_connected_census_blocks"
    location: "brokenspoke"
    target: "neighborhood_connected_census_blocks"
    parameters:
      schema: "brokenspoke"

config:
  meerschaum:
    instance: sql:bwg
    connectors:
      sql:
        bwg: MRSM{meerschaum:connectors:sql:bwg}
  plugins:
    bwg:
      data_path: './data'

environment: {}
