plugins_dir:
  - "plugins"

sync:
  pipes:
    - connector: "plugin:scdps"
      metric: "collisions"
      location: "greenville"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "block_groups"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "distance"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "grid"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "metro_area"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "state"

    - connector: "plugin:streetlights"
      metric: "home"
      location: "zip_codes"

    - connector: "plugin:streetlights"
      metric: "work"
      location: "block_groups"

    - connector: "plugin:streetlights"
      metric: "work"
      location: "distance"

    - connector: "plugin:streetlights"
      metric: "work"
      location: "grid"

config:
  meerschaum:
    instance: "sql:traffic"
    connectors:
      sql:
        traffic: MRSM{meerschaum:connectors:sql:main}
